version: '3'
services:
  groundcontrol_db:
    image: mariadb:latest
    container_name: groundcontrol_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mariadb_password
      MYSQL_DATABASE: groundcontrol
      MYSQL_USER: groundcontrol
      MYSQL_PASSWORD: groundcontrol
    networks:
      - groundcontrolnet
    volumes:
      - groundcontrol_db:/var/lib/mysql
  groundcontrol:
    container_name: groundcontrol
    restart: unless-stopped
    ports:
      - "3001:3001"
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on: [ groundcontrol_db ]
    environment:
      JAWSDB_MARIA_URL: mysql://groundcontrol:groundcontrol@groundcontrol_db:3306/groundcontrol
      FCM_SERVER_KEY: $FCM_SERVER_KEY
      APNS_P8: $APNS_P8
      APNS_P8_KID: $APNS_P8_KID
      APPLE_TEAM_ID: $APPLE_TEAM_ID
      APNS_TOPIC: $APNS_TOPIC
      VERBOSE: true
    networks:
      - groundcontrolnet
networks:
  groundcontrolnet:
volumes:
  groundcontrol_db: